// Code generated by goctl. DO NOT EDIT.
package types

type GeneralIDRequest struct {
	ID int `path:"id"`
}

type GeneralResponse struct {
	Msg string `json:"msg"`
}

type GroupModel struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	CreateAt int64  `json:"create_at"`
	UpdateAt int64  `json:"update_at"`
	DeleteAt int64  `json:"delete_at"`
}

type CreateGroupRequest struct {
	Name string `form:"name"`
}

type UpdateGroupRequest struct {
}

type RetrieveGroupResponse struct {
}

type QuestionModel struct {
}

type CreateQuestionRequest struct {
}

type UpdateQuestionRequest struct {
}

type RetrieveQuestionResponse struct {
}

type AnswerModel struct {
}

type CreateAnswerRequest struct {
}

type UpdateAnswerRequest struct {
}

type RetrieveAnswerResponse struct {
}
